version: '3.8'

services:
  filebrowser:
    image: hurlenko/filebrowser
    container_name: filebrowser_tarea3
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./filebrowser:/srv
    environment:
      - FB_USER=admin
      - FB_PASS=admin
    networks:
      - filebrowser_net

networks:
  filebrowser_net:
